server:
  port: 8071
spring:
  application:
    name: eureka-server
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#server specific messages
eureka-server:
  msg: "From Eureka DEFAULT env"
