server:
  port: ${PORT:0}

## Spring information
spring:
  application:
    name: visitor-guest-service
  config:
    import:
      - optional:configserver:http://localhost:8012/

## Eureka information
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8071/eureka/

## Actuator end point and app information
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

## Service information
info:
  app:
    name: Visitor and guest service
    description: Visitor and guest management
    version: 1.0.0
    env: "DEV"

visitor-guest-service:
  msg: "from dev env"
  build-version: 1.0
